# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('navy', 'azul'), ('aqua', 'aqua'), ('purple', 'Morado'), ('yellow', 'Amarillo'), ('teal', 'turquesa'), ('red', 'rojo'), ('green', 'verde')], default='purple', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
                'verbose_name': 'Etiqueta',
                'ordering': ('etiqueta',),
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('parrafo', models.CharField(max_length=50)),
                ('foto', easy_thumbnails.fields.ThumbnailerImageField(upload_to='post_image')),
                ('etiquetas', models.ManyToManyField(related_name='publicacion', to='publi.Etiqueta')),
            ],
        ),
    ]
