# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='parrafo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
