# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-02 14:14
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0003_auto_20170427_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='post_image'),
        ),
    ]
